A minor fix for @returns document
jasraj/q-doc pull request #7
Opened 2017-03-17 07:36 UTC by FlyingOE

@returns document loses first word of the description

2017-03-20 12:30 UTC, jasraj requested changes
Thanks for submitting these changes! It all looks great except for one minor change which I've commented.

Once you make that change then I will merge.

2017-03-20 12:30 UTC, jasraj commented on html/js/q-doc.js
> +                func: S(element.see[sCount]).humanize(),
You should remove the call to humanize here. For functions with camel-casing (e.g. `.qdoc.getCwd`) is renders as `.qdoc.get cwd` which is incorrect.

2017-03-20 12:30 UTC, jasraj commented on html/js/q-doc.js
> +                func: S(element.see[sCount]).humanize(),
`func: element.see[sCount]` should be enough

2017-03-21 00:43 UTC, FlyingOE commented on html/js/q-doc.js
> +                func: S(element.see[sCount]).humanize(),
Good point! I overlooked that. Updated.

2017-03-21 11:33 UTC, jasraj approved these changes

2017-03-21 11:34 UTC, merged